### ISSUE TITLE
Recent Popular Manga on Mangadex Home

### ISSUE THREAD

**Issue by tonymushah** [tonymushah/special-eureka#21]
## Goal : 

# Listing the top ten recently popular titles in mangadex 

It's like in the Mangadex Home Page 

### Tasks : 

- [x] Create a new React Component that use (approximately) the same as Mangadex website
- [x] Find the actual API request that give the recently popular titles
- [x] Create a new React Swipper Component that contain the top list

### Optional : 

- [x] Create a page to see the full top list
- [x] Create a route to go to that page
- [x] Find a way to go to this page via the sidebar

**Comment by tonymushah** [comment]
Task well done, everything is added. I don't know about the bugs but yeah
